leftnav:
- identifier: 419b2d03-fb9b-1983-257a-041186c0d4cf
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: e574b828-54c9-ab0d-3ef4-9eb6e0b3df72
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 81bcd7a6-98e8-f7a0-6ae7-c74acf3be1e0
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: f2ee3d56-405e-65a1-cb08-e63056ed6ca3
  name: Assignments
  pageRef: /pages/assignments
  weight: 40
- identifier: 27422620-efa8-2dce-c8e8-c59eb7767e9b
  name: Projects
  pageRef: /pages/projects
  weight: 50
